#!/bin/bash

#SBATCH -J my_job
#SBATCH -o my_job.%j.out
#SBATCH -e my_job.%j.err
#SBATCH -N 4
#SBATCH -n 96
#SBATCH -t 48:00:00

#SBATCH --mail-user=
#SBATCH --mail-type=begin
#SBATCH --mail-type=end

mpiexec -np 96 ./mitgcmuv
