#!/bin/bash

### Load modules ### 
#default: intel/13.0.2.146
#default: mvapich2/1.9a2
module load netcdf	
module load parallel-netcdf

### Add staf to path ### 
PATH=$PATH:$HOME/local/bin
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/local/lib

### CVS Stuff ###
export CVSROOT=':pserver:cvsanon@mitgcm.org:/u/gcmpack'
export CVSEDITOR=vim

### MITgcm stuff ###
export MPI_INC_DIR=$MPICH_HOME/include
export NETCDF_BIN=$TACC_NETCDF_BIN
export NETCDF_ROOT=$TACC_NETCDF_DIR
export NETCDF_INC=$TACC_NETCDF_INC
export NETCDF_LIB=$TACC_NETCDF_LIB

## Misc Terminal ##

## Not necessary but convenient
#  export PS1="[stampede \W]\$ "
#  alias ll='ls -al'
