#!/bin/bash

### Load modules ### 
# TACC, intel, and cray_mpich are default modules 
# however, this ensures that they are loaded
module purge
module load TACC
module load intel
module load cray_mpich
module load netcdf	

### Add local binaries/libraries to path ### 
PATH=$PATH:$HOME/local/bin
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/local/lib

### CVS Stuff ###
export CVSROOT=':pserver:cvsanon@mitgcm.org:/u/gcmpack'
export CVSEDITOR=vim

### MITgcm stuff ###
export MPI_INC_DIR=$MPICH_DIR/include
export NETCDF_BIN=$TACC_NETCDF_BIN
export NETCDF_ROOT=$TACC_NETCDF_DIR
export NETCDF_INC=$TACC_NETCDF_INC
export NETCDF_LIB=$TACC_NETCDF_LIB

## Misc terminal ##

## These aren't necessary but are nice
#  export PS1='[lonestar \W]\$ '
#  alias ll='ls -al'

## Increase stack size
ulimit -s hard
ulimit -u hard

### Expand environment variables in tab completion ###
shopt -s direxpand
