#!/bin/bash 

### For MITgcm ###
export CVSROOT=':pserver:cvsanon@mitgcm.org:/u/gcmpack'
export CVSEDITOR=vim

### Modules ###
#module use /share/modulefiles/intel -> no longer necessary
#module load c7 intel/17.0 17.0/openmpi/1.10.2-hfi -> compiler errors
module load c7 intel/17.0 openmpi/2.0.1 

## MITgcm environment variables
export MPI_INC_DIR=$MPI_DIR/include
