#!/bin/bash

### Greeting ###
#echo 'Hello, Bunny!'

### Load modules ### 
myhost=$(hostname -f)
myhost=${myhost%.tacc.utexas.edu}
first=${myhost%%.*}
SYSHOST=${myhost#*.}
first5=$(expr substr $first 1 5)

if [ "$SYSHOST" = "stampede2" ]; then
    source bashrc_stampede2
fi
if [ "$SYSHOST" = "ls5" ]; then
    source bashrc_lonestar
fi
if [ "$SYSHOST" = "sverdrup" ]; then
    source bashrc_sverdrup
fi

### Add local binaries to path ### 
PATH=$PATH:$HOME/bin:$HOME/local/bin

### Insert aliases here ###
# All of these can be commented out
alias ..='cd ..'
alias ll='ls -la'
alias date='date +%Y/%m/%d" "%T.%N'
