#!/bin/bash
#
# For running on TACC's Stampede
#  Compiler optimizations for Intel E5-2680 (Ivy Bridge) Processors
#
# Note: be sure to load the following modules
#
#  module load netcdf
#  module load parallel-netcdf
#  
#  (default) module load intel
#  (default) module load mvapich2 
#
#-------

CC=icc
FC=ifort
F90C=ifort
LINK="$F90C -no-ipo"

DEFINES='-DALLOW_USE_MPI -DALWAYS_USE_MPI -DWORDLENGTH=4'
CPP='cpp -traditional -P'
F90FIXEDFORMAT='-fixed -Tf'
EXTENDED_SRC_FLAG='-132'
GET_FC_VERSION="--version"
OMPFLAG='-openmp'

#NOOPTFLAGS='-O0 -g'
NOOPTFILES='01 -fp-model precise'

FFLAGS="$FFLAGS -W0 -WB -convert big_endian -assume byterecl"
FFLAGS="$FFLAGS -fPIC"
#- might want to use '-r8' for fizhi pkg:
#FFLAGS="$FFLAGS -r8"

if test "x$IEEE" = x ; then     #- with optimisation:
    FOPTIM='-O2 -align -traceback -xAVX -ip -ftz -fp-model precise'
    NOOPTFILES='seaice_growth.F calc_oce_mxlayer.F fizhi_lsm.F fizhi_clockstuff.F'
else
  if test "x$DEVEL" = x ; then  #- no optimisation + IEEE :
    # "-mp" is for ieee "maintain precision"
    FOPTIM='-O0 -noalign -traceback -xAVX -ip -mp'
  else                          #- development/check options:
    FFLAGS="$FFLAGS -warn all -warn nounused"
    FOPTIM="-fpe0 -fpstkchk -fpmodel except -check all -ftrapuv"
    FOPTIM="-O0 -noalign -g -traceback"
  fi
fi

F90FLAGS=$FFLAGS
F90OPTIM=$FOPTIM
CFLAGS='-O0 -ip -fPIC'

INCLUDEDIRS="${MPICH_HOME}/include ${TACC_NETCDF_INC}"
INCLUDES="-I${MPICH_HOME}/include -I${TACC_NETCDF_INC}"
LIBS="-L${MPICH_HOME}/lib -lmpich -L${TACC_NETCDF_LIB} -lnetcdf -lnetcdff"
#- used for parallel (MPI) DIVA
MPIINCLUDEDIR="${MPICH_HOME}"
