#!/bin/bash
#
# For running on TACC's Lonestar 6, AMD Epyc Milan processors
#
# Make sure the following modules are loaded:
#   intel/19.1.1 impi/19.0.9 netcdf/4.6.2 

CC=icc
FC=ifort
F90C=ifort
LINK="$F90C -no-ipo"

DEFINES='-DALLOW_USE_MPI -DALWAYS_USE_MPI -DWORDLENGTH=4'
CPP='cpp -traditional -P'
F90FIXEDFORMAT='-fixed -Tf'
EXTENDED_SRC_FLAG='-132'
GET_FC_VERSION="--version"
OMPFLAG='-openmp'

NOOPTFLAGS='-O1 -fp-model precise'

FFLAGS="$FFLAGS -W0 -WB -convert big_endian -assume byterecl"
FFLAGS="$FFLAGS -fPIC"
FFLAGS="$FFLAGS -mcmodel=large -shared-intel"
FFLAGS="$FFLAGS -132" # extend to 132 columns

if test "x$IEEE" = x ; then
    FOPTIM="-align -traceback       -O3 -ip -ftz -fp-model precise"
    NOOPTFILES='obcs_set_connect.F obcs_init_fixed.F'
else
    if test "x$DEVEL" = x ; then
        FOPTIM='-O0 -noalign -traceback      -ip -mp'
    else
        FFLAGS="$FFLAGS -warn all -warn nounused"
        FOPTIM="-O0 -noalign -g -traceback"
    fi
fi

F90FLAGS=$FFLAGS
F90OPTIM=$FOPTIM
CFLAGS="-O3 -ip -fPIC"

INCLUDEDIRS="${TACC_IMPI_INC} ${TACC_NETCDF_INC}"
INCLUDES="-I${TACC_IMPI_INC} -I${TACC_NETCDF_INC}"
LIBS="-L${TACC_IMPI_LIB}/release -L${TACC_IMPI_LIB} -lmpi -lmpifort -L${TACC_NETCDF_LIB} -lnetcdf -lnetcdff"
MPIINCLUDEDIR="${TACC_IMPI_INC}"
