#!/bin/bash
#
# For running on TACC's Stampede 2, skylake nodes
#
# Make sure the following modules are loaded:
#   intel/17.0.4 impi/17.0.3 netcdf/4.3.3.1 

CC=icc
FC=ifort
F90C=ifort
LINK="$F90C -no-ipo"

DEFINES='-DALLOW_USE_MPI -DALWAYS_USE_MPI -DWORDLENGTH=4 -DINTEL_COMMITQQ'
CPP='cpp -traditional -P'
F90FIXEDFORMAT='-fixed -Tf'
EXTENDED_SRC_FLAG='-132'
GET_FC_VERSION="--version"
OMPFLAG='-openmp'

NOOPTFLAGS='-O1 -fp-model precise'

FFLAGS="$FFLAGS -W0 -WB -convert big_endian -assume byterecl"
FFLAGS="$FFLAGS -fPIC"
FFLAGS="$FFLAGS -mcmodel=large -shared-intel"

if test "x$IEEE" = x ; then
    FOPTIM="-align -traceback -xCORE-AVX512 -O3 -ip -ftz -fp-model precise"
    NOOPTFILES='seaice_growth.F calc_oce_mxlayer.F fizhi_lsm.F fizhi_clockstuff.F'
else
    if test "x$DEVEL" = x ; then
        FOPTIM='-O0 -noalign -traceback -xCORE-AVX512 -ip -mp'
    else
        FFLAGS="$FFLAGS -warn all -warn nounused"
        NOOPTFILES='adread_adwrite.F mdsio_rw_field.F mdsio_rw_slice.F'
        FOPTIM="-fpe0 -fpstkchk -fpmodel except -check all -ftrapuv"
        FOPTIM="-O0 -noalign -g -traceback"
    fi
fi

F90FLAGS=$FFLAGS
F90OPTIM=$FOPTIM
CFLAGS="-O3 -ip -fPIC"

# From running: `mpiifort -show`
INCLUDEDIRS="${TACC_IMPI_INC} ${TACC_NETCDF_INC}"
INCLUDES="-I${TACC_IMPI_INC} -I${TACC_NETCDF_INC}"
LIBS="-L${TACC_IMPI_LIB}/release -L${TACC_IMPI_LIB} -lmpi -lmpifort -L${TACC_NETCDF_LIB} -lnetcdf -lnetcdff"
MPIINCLUDEDIR="${TACC_IMPI_INC}"

